### ISSUE TITLE
Font Color in week view editable

### ISSUE THREAD

**Issue by lomarence** [pyxelr/Dark_Google_Calendar#18]
Thank you for the new font color option. But it only works in the month view. Could you make it work for every other view?

**Comment by pyxelr** [comment]
@Oronhyatekha: Could you please double-check it? In my case, modifying the font colour applies it in all the views (month, week, day, and schedule) for all the future events.

Here is an example with a past and future event in the week view:
![2023-06-03_00-40-56](https://github.com/pyxelr/dark-google-calendar/assets/30161753/4f2d30ef-20ee-44bc-b666-e56f56fa5d49)

**Comment by lomarence** [comment]
It does not work for future events but for past events

![Screenshot 2023-06-08 091744](https://github.com/pyxelr/dark-google-calendar/assets/14246140/b8fec865-6454-4b2a-b07f-ce3cd3d23c2e)

**Comment by pyxelr** [comment]
@Oronhyatekha: Please have a look at it now. Version `2.7.16` should resolve this problem.

**Comment by lomarence** [comment]
Sadly that doesn't solve the issue. The colors stay the same. Could it be my browser (Edge)?

**Comment by pyxelr** [comment]
I'm unsure. Please try reinstalling this theme, and eventually giving it a try in Chrome.

If it still does not work, please paste a similar screenshot to mine above (with the selected colors) so that I could see what does not work for you exactly.
